// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCX2at3vZ2C8oBhjqyOf1PWwZcjSbokwUU',
    appId: '1:373014830594:web:1df3d1cfb513092fad511b',
    messagingSenderId: '373014830594',
    projectId: 'celenganku-a3cdc',
    authDomain: 'celenganku-a3cdc.firebaseapp.com',
    storageBucket: 'celenganku-a3cdc.firebasestorage.app',
    measurementId: 'G-EVEV1ZXVVF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDE9IKcGeO7OOSq3iniGizVibZ58J9Eg98',
    appId: '1:373014830594:android:6e3dcb263ad06aafad511b',
    messagingSenderId: '373014830594',
    projectId: 'celenganku-a3cdc',
    storageBucket: 'celenganku-a3cdc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-nhyFuk4RMfF0bAQoJsEwWgPx5IVYgGU',
    appId: '1:373014830594:ios:cef267e8f26aa689ad511b',
    messagingSenderId: '373014830594',
    projectId: 'celenganku-a3cdc',
    storageBucket: 'celenganku-a3cdc.firebasestorage.app',
    androidClientId: '373014830594-tq8gu76r1hku7s9hjdo12kj94ts6h8ni.apps.googleusercontent.com',
    iosClientId: '373014830594-bf321d5k71u98fb3df9mh6n7res703sl.apps.googleusercontent.com',
    iosBundleId: 'com.example.celenganku',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-nhyFuk4RMfF0bAQoJsEwWgPx5IVYgGU',
    appId: '1:373014830594:ios:cef267e8f26aa689ad511b',
    messagingSenderId: '373014830594',
    projectId: 'celenganku-a3cdc',
    storageBucket: 'celenganku-a3cdc.firebasestorage.app',
    androidClientId: '373014830594-tq8gu76r1hku7s9hjdo12kj94ts6h8ni.apps.googleusercontent.com',
    iosClientId: '373014830594-bf321d5k71u98fb3df9mh6n7res703sl.apps.googleusercontent.com',
    iosBundleId: 'com.example.celenganku',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCX2at3vZ2C8oBhjqyOf1PWwZcjSbokwUU',
    appId: '1:373014830594:web:c28991f27080bc7aad511b',
    messagingSenderId: '373014830594',
    projectId: 'celenganku-a3cdc',
    authDomain: 'celenganku-a3cdc.firebaseapp.com',
    storageBucket: 'celenganku-a3cdc.firebasestorage.app',
    measurementId: 'G-VJS884E1XC',
  );
}
